repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        files: ^(thesync-backend|thesync-frontend)/
      - id: end-of-file-fixer
        files: ^(thesync-backend|thesync-frontend)/
      - id: trailing-whitespace
        files: ^(thesync-backend|thesync-frontend)/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        files: ^thesync-backend/
        args: [--fix, --config=thesync-backend/pyproject.toml]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: thesync-backend/.venv/bin/python -m black --config thesync-backend/pyproject.toml
        language: system
        files: ^thesync-backend/
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: ^thesync-backend/
        args: [--config=thesync-backend/.flake8]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        files: ^thesync-backend/

  - repo: local
    hooks:
      - id: frontend-ci-checks
        name: frontend-ci-checks
        entry: make
        args: [-C, thesync-frontend, ci-checks]
        language: system
        pass_filenames: false
        files: ^thesync-frontend/
