repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        files: ^(thesync-backend|thesync-frontend)/
      - id: end-of-file-fixer
        files: ^(thesync-backend|thesync-frontend)/
      - id: trailing-whitespace
        files: ^(thesync-backend|thesync-frontend)/

  - repo: local
    hooks:
      - id: frontend-ci-checks
        name: frontend-ci-checks
        entry: make
        args: [-C, thesync-frontend, ci-checks]
        language: system
        pass_filenames: false
        files: ^thesync-frontend/
        always_run: true
